Models/Employee.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCCRUD2.Models
{
    public class Employee
    {
        internal object Skill;

        [Key]
        public int EmpId { get; set; }
        public string Username { get; set; } = default!;
        public string Password { get; set; } = default!;
        public string Email { get; set; } = default!;
        public DateTime DOB { get; set; }   
        public string Phone { get; set; } = default!;
        public string Address { get; set; } = default!;
        public string Gender { get; set; } = default!;
        public char RecStatus { get; set; } = 'A';
        
        //public int EmpSkillId { get; set; }
        //[ForeignKey("EmpSkill")]
        //public EmpSkill EmpSkill { get; set; } = default!;
    }
}

Controllers/AuthenticateController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCCRUD2.Data;
using MVCCRUD2.Models;

namespace MVCCRUD2.Controllers
{
    public class AuthenticateController : Controller
    {
        private readonly ApplicationContext context;

        public AuthenticateController(ApplicationContext context)
        {
            this.context = context;
        }
        [HttpGet]
        public IActionResult Login()
        {
            // var employees = await mvcDemoDbContext.Employees.Where(x => x.RecStatus == 'A').OrderBy(x => x.Username).ToListAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Employee emp)
        {
            if (emp.Username == "Bipin" && emp.Password == "123")
            {
                // Authentication successful
                var employees = await context.Employees.Where(x => x.Username == emp.Username && x.Password == emp.Password).ToListAsync();
                return RedirectToAction("Index", "Employees", employees);
            }

            ModelState.AddModelError("", "Invalid username or password.");

            TempData["ErrorMessage"] = "Invalid username or password.";
            return View();
        }
    }
}

Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCCRUD2.Data;
using MVCCRUD2.Models;
using MVCCRUD2.Models.ViewModel;

namespace MVCCRUD2.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ApplicationContext context;

        public EmployeesController(ApplicationContext context)
        {
            this.context = context;
        }


        public IActionResult Index()
        {
            //EmpSkillsListViewModel empSkills = new EmpSkillsListViewModel();
            //empSkills.employees = context.Employees.ToList();
            //empSkills.skill = context.Skills.ToList();

            var data = (from e in context.Employees
                        join s in context.Skills
                        on e.EmpId equals s.SkillId 
                        select new EmpSkillSummaryModel
                        {
                            EmpId = e.EmpId,
                            Username = e.Username,
                            Password = e.Password,
                            Email = e.Email,
                            DOB = e.DOB,
                            Address = e.Address,
                            Phone = e.Phone,
                            Gender = e.Gender,
                            RecStatus = e.RecStatus,
                            Java = s.Java,
                            Python = s.Python,
                            CPlusPlus = s.CPlusPlus
                        }).Where(x => x.RecStatus == 'A').OrderBy(x => x.Username).ToList();

            return View(data);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(EmpSkillSummaryModel addEmployeeRequest)
        {
            var employee = new Employee()
            {
                EmpId = addEmployeeRequest.EmpId,
                Username = addEmployeeRequest.Username,
                Password = addEmployeeRequest.Password,
                DOB = addEmployeeRequest.DOB,
                Email = addEmployeeRequest.Email,
                Address = addEmployeeRequest.Address,
                Phone = addEmployeeRequest.Phone,
                Gender = addEmployeeRequest.Gender,
                RecStatus = addEmployeeRequest.RecStatus
            };

            var skill = new Skill()
            {
                Java = addEmployeeRequest.Java,
                Python = addEmployeeRequest.Python,
                CPlusPlus = addEmployeeRequest.CPlusPlus
            };

            await context.Employees.AddAsync(employee);
            await context.SaveChangesAsync();

            await context.Skills.AddAsync(skill);
            await context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(int id)
        {
            var employee = await context.Employees.FirstOrDefaultAsync(x => x.EmpId == id);

            var skill = await context.Skills.FirstOrDefaultAsync(x => x.SkillId == id);

            if (employee != null && skill != null)
            {
                var viewModel = new UpdateEmployeeViewModel()
                {
                    EmpId = employee.EmpId,
                    Username = employee.Username,
                    Password = employee.Password,
                    DOB = employee.DOB,
                    Email = employee.Email,
                    Address = employee.Address,
                    Phone = employee.Phone,
                    Gender = employee.Gender,
                    Java = skill.Java,
                    Python = skill.Python,
                    CPlusPlus = skill.CPlusPlus,
                    RecStatus = employee.RecStatus,
                };

                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateEmployeeViewModel model)
        {
            var employee = await context.Employees.FindAsync(model.EmpId);

            var skill = await context.Skills.FindAsync(model.EmpId);

            if (employee != null && skill != null)
            {
                employee.Username = model.Username;
                employee.Password = model.Password;
                employee.DOB = model.DOB;
                employee.Email = model.Email;
                employee.Address = model.Address;
                employee.Phone = model.Phone;
                employee.Gender = model.Gender;
                skill.Python = model.Python;
                skill.Java = model.Java;
                skill.CPlusPlus = model.CPlusPlus;
                employee.RecStatus = model.RecStatus;

                await context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        //public async Task<IActionResult> Delete(int id)
        //{
        //    var employee = await context.Employees.FindAsync(id);

        //    var skill = await context.Skills.FindAsync(id);

        //    if (employee != null && skill != null)
        //    {
        //        employee.RecStatus = 'D';

        //        // for deleting a record use the below code. 
        //        // mvcDemoDbContext.Employees.Remove(employee);

        //        await context.SaveChangesAsync();

        //        return RedirectToAction("Index");
        //    }

        //    return RedirectToAction("Index");
        //}

        public async Task<IActionResult> SoftDelete(int id)
        {
            var employee = await context.Employees.FindAsync(id);
            

            if (employee != null)
            {
                employee.RecStatus = 'D';

                await context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        public IActionResult DeleteIndex()
        {
            var data = (from e in context.Employees
                        join s in context.Skills
                        on e.EmpId equals s.SkillId
                        select new EmpSkillSummaryModel
                        {
                            EmpId = e.EmpId,
                            Username = e.Username,
                            Password = e.Password,
                            Email = e.Email,
                            DOB = e.DOB,
                            Address = e.Address,
                            Phone = e.Phone,
                            Gender = e.Gender,
                            RecStatus = e.RecStatus,
                            Java = s.Java,
                            Python = s.Python,
                            CPlusPlus = s.CPlusPlus
                        }).Where(x => x.RecStatus == 'D').OrderBy(x => x.Username).ToList();

            return View(data);
        }

        public async Task<IActionResult> Recover(int id)
        {
            var deletedRecord = context.Employees.FirstOrDefault(x => x.EmpId == id);

            if (deletedRecord != null)
            {
                deletedRecord.RecStatus = 'A';
                context.Employees.Update(deletedRecord);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> HardDelete(int id)
        {
            var employee = context.Employees.FirstOrDefault(x => x.EmpId == id);

            if (employee != null)
            {
                employee.RecStatus = 'D';

                // for deleting a record use the below code. 
                context.Employees.Remove(employee);
                await context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }
    }
}

Views/Employees/Add.cshtml
@model MVCCRUD2.Models.ViewModel.EmpSkillSummaryModel
@{
    ViewData["Title"] = "Add";
}
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Employees" asp-action="Index">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Add">Add Employee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="DeleteIndex">Restore Employee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Authenticate" asp-action="Login">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<form method="post" action="Add" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Username</label>
        <input type="text" class="form-control" asp-for="Username" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Password</label>
        <input type="password" class="form-control" asp-for="Password" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Date Of Birth</label>
        <input type="date" class="form-control" asp-for="DOB" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Email Address</label>
        <input type="email" class="form-control" asp-for="Email" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Address</label>
        <input type="text" class="form-control" asp-for="Address" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Phone Number</label>
        <input type="text" class="form-control" asp-for="Phone" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Gender</label>
        <div class="row">
            <div class="col-sm-2">
                <div class="form-check">
                    <input type="radio" class="form-check-input" name="gender" value="Male" asp-for="Gender" required>
                    <label class="form-check-label">Male</label>
                </div>
            </div>
            <div class="col-sm-2" style="margin-left:-6px">
                <div class="form-check">
                    <input type="radio" class="form-check-input" name="gender" value="Female" asp-for="Gender" required>
                    <label class="form-check-label">Female</label>
                </div>
            </div>
        </div>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Skills</label>
        <div class="row" style="width:100%">
            <div class="col-sm-2">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="Python" value="true" asp-for="Python">
                    <label class="form-check-label">Python</label>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="Java" value="true" asp-for="Java">
                    <label class="form-check-label">Java</label>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="CPlusPLus" value="true" asp-for="CPlusPlus">
                    <label class="form-check-label">C++</label>
                </div>
            </div>
        </div>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/Employees/DeleteIndex.cshtml
@model IEnumerable<MVCCRUD2.Models.ViewModel.EmpSkillSummaryModel>

@*@model MVCCRUD2.Models.ViewModel.EmpSkillsListViewModel*@

@{
    ViewData["Title"] = "Index";
}


<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Employees" asp-action="Index">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Add">Add Employee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="DeleteIndex">Restore Employee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Authenticate" asp-action="Login">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<table class="table">
    <thead>
        <tr>
            <th>Username</th>
            <th>Password</th>
            <th>Date of Birth</th>
            <th>Email Address</th>
            <th>Address</th>
            <th>Phone Number</th>
            <th>Skills</th>
            <th>Gender</th>
            <th>Action</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.Username</td>
                <td>
                    @for (int i = 1; i <= employee.Password.Length; i++)
                    {
                        <h5 style="display:inline">*</h5>
                    }
                </td>

                <td>@employee.DOB.ToString("dd-MM-yyyy")</td>
                <td>@employee.Email</td>
                <td>@employee.Address</td>
                <td>@employee.Phone</td>
                <td>
                    @if (employee.Python == "true" && employee.Java == "true" && employee.CPlusPlus == "true")
                    {
                        <p>Python, Java and C++</p>
                    }
                    else if (employee.Python == "true" && employee.Java == "true" && employee.CPlusPlus != "true")
                    {
                        <p>Python and Java</p>
                    }
                    else if (employee.Python == "true" && employee.Java != "true" && employee.CPlusPlus == "true")
                    {
                        <p>Python and C++</p>
                    }
                    else if (employee.Python != "true" && employee.Java == "true" && employee.CPlusPlus == "true")
                    {
                        <p>Java and C++</p>
                    }
                    else if (employee.Python == "true" && employee.Java != "true" && employee.CPlusPlus != "true")
                    {
                        <p>Python</p>
                    }
                    else if (employee.Python != "true" && employee.Java == "true" && employee.CPlusPlus != "true")
                    {
                        <p>Java</p>
                    }
                    else if (employee.Python != "true" && employee.Java != "true" && employee.CPlusPlus == "true")
                    {
                        <p>C++</p>
                    }
                    else
                    {
                        <p>No skills for @employee.Username</p>
                    }
                </td>
                <td>@employee.Gender</td>

                <td>
                    <button type="submit" class="btn btn-danger btn-sm">
                        <a style="color:white; text-decoration:none" asp-action="Recover" asp-route-id="@employee.EmpId">Recover</a>
                    </button>
                </td>
                <td>
                    <button type="submit" class="btn btn-danger btn-sm">
                        <a style="color:white; text-decoration:none" asp-action="HardDelete" asp-route-id="@employee.EmpId">Delete</a>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Employees/Index.cshtml
@model IEnumerable<MVCCRUD2.Models.ViewModel.EmpSkillSummaryModel>

@*@model MVCCRUD2.Models.ViewModel.EmpSkillsListViewModel*@

@{
    ViewData["Title"] = "Index";
}

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Employees" asp-action="Index">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Add">Add Employee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="DeleteIndex">Restore Employee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Authenticate" asp-action="Login">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<table class="table">
    <thead>
        <tr>
            <th>Username</th>
            <th>Password</th>
            <th>Date of Birth</th>
            <th>Email Address</th>
            <th>Address</th>
            <th>Phone Number</th>
            <th>Skills</th>
            <th>Gender</th>
            <th>Action</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.Username</td>
                <td>@for (int i = 1; i <= employee.Password.Length; i++)
                    {
                        <h5 style="display:inline">*</h5>
                    }
                </td>

                <td>@employee.DOB.ToString("dd-MM-yyyy")</td>
                <td>@employee.Email</td>
                <td>@employee.Address</td>
                <td>@employee.Phone</td>
                <td>
                    @if (employee.Python == "true" && employee.Java == "true" && employee.CPlusPlus == "true")
                    {
                        <p>Python, Java and C++</p>
                    }
                    else if (employee.Python == "true" && employee.Java == "true" && employee.CPlusPlus != "true")
                    {
                        <p>Python and Java</p>
                    }
                    else if (employee.Python == "true" && employee.Java != "true" && employee.CPlusPlus == "true")
                    {
                        <p>Python and C++</p>
                    }
                    else if (employee.Python != "true" && employee.Java == "true" && employee.CPlusPlus == "true")
                    {
                        <p>Java and C++</p>
                    }
                    else if (employee.Python == "true" && employee.Java != "true" && employee.CPlusPlus != "true")
                    {
                        <p>Python</p>
                    }
                    else if (employee.Python != "true" && employee.Java == "true" && employee.CPlusPlus != "true")
                    {
                        <p>Java</p>
                    }
                    else if (employee.Python != "true" && employee.Java != "true" && employee.CPlusPlus == "true")
                    {
                        <p>C++</p>
                    }
                    else
                    {
                        <p>No skills for @employee.Username</p>
                    }
                </td>
                <td>@employee.Gender</td>
                
                <td>
                    <button type="submit" class="btn btn-primary btn-sm">
                        <a style="color:white; text-decoration:none" href="@Url.ActionLink("View","Employees",new{Id = employee.EmpId})">Edit</a>
                    </button>
                </td>
                <td>
                    <button type="submit" class="btn btn-danger btn-sm">
                        <a style="color:white; text-decoration:none" asp-action="SoftDelete" asp-route-id="@employee.EmpId"> Delete</a>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Employees/View.cshtml
@model MVCCRUD2.Models.UpdateEmployeeViewModel
@{
    ViewData["Title"] = "View";
}


<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Employees" asp-action="Index">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Add">Add Employee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="DeleteIndex">Restore Employee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Authenticate" asp-action="Login">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<h1 style="text-align:center; margin-bottom: 10px">Edit Employee</h1>
<form method="post" action="View" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="EmpId" readonly>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Username</label>
        <input type="text" class="form-control" asp-for="Username" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Password</label>
        <input type="text" class="form-control" asp-for="Password" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Date Of Birth</label>
        <input type="date" class="form-control" asp-for="DOB" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Email Address</label>
        <input type="email" class="form-control" asp-for="Email" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Address</label>
        <input type="text" class="form-control" asp-for="Address" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Phone Number</label>
        <input type="text" class="form-control" asp-for="Phone" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Gender</label>
        <div class="row">
            <div class="col-sm-2">
                <div class="form-check">
                    <input type="radio" class="form-check-input" name="gender" value="Male" asp-for="Gender" required>
                    <label class="form-check-label">Male</label>
                </div>
            </div>
            <div class="col-sm-2" style="margin-left:-6px">
                <div class="form-check">
                    <input type="radio" class="form-check-input" name="gender" value="Female" asp-for="Gender" required>
                    <label class="form-check-label">Female</label>
                </div>
            </div>
        </div>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Skills</label>
        <div class="row" style="width:100%">
            <div class="col-sm-2">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="Python" value="true" asp-for="Python">
                    <label class="form-check-label">Python</label>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="Java" value="true" asp-for="Java">
                    <label class="form-check-label">Java</label>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="CPlusPLus" value="true" asp-for="CPlusPlus">
                    <label class="form-check-label">C++</label>
                </div>
            </div>
        </div>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Edit</button>
    @*<button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Employees">Delete</button>*@
</form>